### ISSUE TITLE
Complete the Get In Touch section

### ISSUE THREAD

**Issue by RyanWalker277** [RyanWalker277/EcoJoy#11]
# Complete the Get In Touch section

## Description
-Complete the functionality , such that the user messages are saved in a seperate model in the backend , from where the admin can see the messages

## Expected outcomes

A working contact system on the website

## Skills

Python, Django

## Possible mentors

[Anvansh](https://github.com/RyanWalker277)

## Expected project size

2 hours.

## Difficulty

Easy

**Comment by RyanWalker277** [comment]
# Complete the Get In Touch section

## Description
-Complete the functionality , such that the user messages are saved in a seperate model in the backend , from where the admin can see the messages

## Expected outcomes

A working contact system on the website

## Skills

Python, Django

## Possible mentors

[Anvansh](https://github.com/RyanWalker277)

## Expected project size

2 hours.

## Difficulty

Easy

**Comment by RyanWalker277** [comment]
# Use This Proposal Template as a Reference to write your own proposal for Msoc

# Your Issue Name

### Your Background and Technical Skills.
<hr>

### What problem are you trying to solve and Your Approach?
<hr>

###  Your Timeline to solve the problem.
<hr>

**Comment by RyanWalker277** [comment]
# Example of Proposal.


# Improve the generated PDF in the PDF/LaTeX backend

### About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 2 years. I
have experienced in Python , JavaScript, and Dart[Flutter] and I am currently learning Julia. I organized events on Open-Source in my College and I am the founding member of an Open-Source community [fossc](https://www.saynotocp.org/) where I mentor Students in their Open-Source Journey. For more information about me You can head over to my [website](https://kanishkpachauri.netlify.app/)
<hr>

### Issue - Intermittent CI failures with PDF builds 
Issue - The "PDF/LaTeX backend" stage often fails on CI, causing the docs not to deploy (since they only deploy if that stage passes) Restarting the build usually fixes it though.

## Proposed Solution….
● Fixing any bug on the CI end.
● Debug any issue in the test of the LaTeX backend
● Rewriting guided Tests for it so that it can be fixed throughout the process.
<hr>

###  TimeLine
## May 20 - June 12
Community bonding, understanding Documenter.jl Codebase, re-scoping project implementation/timeline with help from mentors.

## June 13 - June 23
Learning Julia Essentials and other essentials for integration and fixing of issue #1196 and #1467 and #1342 .

## June 24 - July 15
Adding the Proposed Solution for the issue #1196 and #1467

<hr>

**Comment by Yash-Var** [comment]
> > > # Complete the Get In Touch section #11
> > > # About me
> > > I'm Yash Varshney . I have experience in  C, C++, HTML, CSS, Python and JavaScript. I am currently doing ReactJS. I am doing open source since 4 month .
> > > # Proposed Solution
> > > I will Complete the functionality , such that the user messages are saved in a seperate model in the backend , from where the admin can see the messages
> > > ## Commitments
> > > 
> > > * I will make sure that issue will be resolved as soon as possible.
> > > * I will try my best to learn everything which is essential for the
> > >   project.

**Comment by Yash-Var** [comment]
@RyanWalker277 i have almost completed but this error comes`
![important](https://user-images.githubusercontent.com/95767787/189498999-fc28284e-d9c0-4904-a490-27068f6ef834.png)

**Comment by RyanWalker277** [comment]
Share your code please

**Comment by Yash-Var** [comment]
i have mail you pls check

**Comment by RyanWalker277** [comment]
Okay , I'll review this and get back to you

**Comment by Yash-Var** [comment]
okk

**Comment by RyanWalker277** [comment]
Try modifying the ids of the input fields according to the api parameters ( rename contact -name to name and so on ) , most likely that's what is causing the issue.Your api accepts parameters as "name" but your request is sending them as "contact -name" , hence the null error occurs.Try testing your api on postman before integrating in frontend

**Comment by Yash-Var** [comment]
change but same error comes

**Comment by Yash-Var** [comment]
its work pls check i made a pr

**Comment by RyanWalker277** [comment]
Always remember to remove the unnecessary comments from your code , reduce the number of lines changed to as less as possible and properly name your commits.Also , always use a gitignore file before making the commit so that the migration files and sqlite files can be ommited from your commit.I have requested some changes in the pr , do these changes so that I can review and merge it.Great work by the way.Keep it up!

**Comment by Yash-Var** [comment]
Okk

**Comment by Yash-Var** [comment]
I have the necessary changes pls review it and  i unable to ommited the migration files ....
