### ISSUE TITLE
Add Black action for code formatting.

### ISSUE THREAD

**Issue by RyanWalker277** [RyanWalker277/EcoJoy#18]
Refrence : https://black.readthedocs.io/en/stable/integrations/github_actions.html

**Comment by prabs222** [comment]
Hello sir @RyanWalker277 , I want to contribute to this issue.

**Comment by RyanWalker277** [comment]
Ya sure @prabs222 ! Go ahead.

**Comment by prabs222** [comment]
@RyanWalker277 Sir please review my PR and please assign this issue.
