### ISSUE TITLE
Complete the plant identification feature

### ISSUE THREAD

**Issue by RyanWalker277** [RyanWalker277/EcoJoy#7]
# Complete the plant identification feature

## Description
-Ypu have to complete the plant identifier , wherin a user uploads a picture of a plant and gets all the information about that
-You can use the plant.id api for completing the feature at https://rakathon2022.pythonanywhere.com/identifier/

## Expected outcomes

A working search bar with all the parts of the results page linked to the correct pages

## Skills

Python, Django

## Possible mentors

[Anvansh](https://github.com/RyanWalker277)

## Expected project size

3 hours.

## Difficulty

Medium

**Comment by RyanWalker277** [comment]
# Use This Proposal Template as a Reference to write your own proposal for Msoc

# Your Issue Name

### Your Background and Technical Skills.
<hr>

### What problem are you trying to solve and Your Approach?
<hr>

###  Your Timeline to solve the problem.
<hr>

**Comment by RyanWalker277** [comment]
# Example of Proposal.


# Improve the generated PDF in the PDF/LaTeX backend

### About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 2 years. I
have experienced in Python , JavaScript, and Dart[Flutter] and I am currently learning Julia. I organized events on Open-Source in my College and I am the founding member of an Open-Source community [fossc](https://www.saynotocp.org/) where I mentor Students in their Open-Source Journey. For more information about me You can head over to my [website](https://kanishkpachauri.netlify.app/)
<hr>

### Issue - Intermittent CI failures with PDF builds 
Issue - The "PDF/LaTeX backend" stage often fails on CI, causing the docs not to deploy (since they only deploy if that stage passes) Restarting the build usually fixes it though.

## Proposed Solution….
● Fixing any bug on the CI end.
● Debug any issue in the test of the LaTeX backend
● Rewriting guided Tests for it so that it can be fixed throughout the process.
<hr>

###  TimeLine
## May 20 - June 12
Community bonding, understanding Documenter.jl Codebase, re-scoping project implementation/timeline with help from mentors.

## June 13 - June 23
Learning Julia Essentials and other essentials for integration and fixing of issue #1196 and #1467 and #1342 .

## June 24 - July 15
Adding the Proposed Solution for the issue #1196 and #1467

<hr>

**Comment by manaswii** [comment]
# Complete the plant identification feature
### Background and Technical Skills.
Knowledge and experience in C++, C, python, flask, SQL, some basic HTML, CSS and JavaScript.
### Proposed Solution
- I'll complete the plant identification feature using plant.id api

### Timeline to solve the problem.
### Sept 20-22
