### ISSUE TITLE
Customize the Django dashboard

### ISSUE THREAD

**Issue by RyanWalker277** [RyanWalker277/EcoJoy#8]
# Customize the Django dashboard

## Description
-Customize the django dashboard with Jazzmin , change the logo and color themes to make it more user friendly

## Expected outcomes

A custokmized dashboard for the website

## Skills

Python, Django

## Possible mentors

[Anvansh](https://github.com/RyanWalker277)

## Expected project size

2 hours.

## Difficulty

Easy

**Comment by RyanWalker277** [comment]
# Use This Proposal Template as a Reference to write your own proposal for Msoc

# Your Issue Name

### Your Background and Technical Skills.
<hr>

### What problem are you trying to solve and Your Approach?
<hr>

###  Your Timeline to solve the problem.
<hr>

**Comment by RyanWalker277** [comment]
# Example of Proposal.


# Improve the generated PDF in the PDF/LaTeX backend

### About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 2 years. I
have experienced in Python , JavaScript, and Dart[Flutter] and I am currently learning Julia. I organized events on Open-Source in my College and I am the founding member of an Open-Source community [fossc](https://www.saynotocp.org/) where I mentor Students in their Open-Source Journey. For more information about me You can head over to my [website](https://kanishkpachauri.netlify.app/)
<hr>

### Issue - Intermittent CI failures with PDF builds 
Issue - The "PDF/LaTeX backend" stage often fails on CI, causing the docs not to deploy (since they only deploy if that stage passes) Restarting the build usually fixes it though.

## Proposed Solution….
● Fixing any bug on the CI end.
● Debug any issue in the test of the LaTeX backend
● Rewriting guided Tests for it so that it can be fixed throughout the process.
<hr>

###  TimeLine
## May 20 - June 12
Community bonding, understanding Documenter.jl Codebase, re-scoping project implementation/timeline with help from mentors.

## June 13 - June 23
Learning Julia Essentials and other essentials for integration and fixing of issue #1196 and #1467 and #1342 .

## June 24 - July 15
Adding the Proposed Solution for the issue #1196 and #1467

<hr>

**Comment by Yash-Var** [comment]
> > > > # Customize the Django dashboard
> > > > # About me
> > > > I'm Yash Varshney . I have experience in  C, C++, HTML, CSS, Python and JavaScript. I am currently doing ReactJS. I am doing open source since 4 month .
> > > > # Proposed Solution
> > > > I will customize the django dashboard with Jazzmin , change the logo and color themes to make it more user friendly
> > > > ## Commitments
> > > > 
> > > > * I will make sure that issue will be resolved as soon as possible.
> > > > * I will try my best to learn everything which is essential for the
> > > >   project.

**Comment by Yash-Var** [comment]
@RyanWalker277 I have make a admin portal by jazzmin, But i am unable to change the logo pls review it and give me some suggestions....
