### ISSUE TITLE
Complete the Blogs Section

### ISSUE THREAD

**Issue by RyanWalker277** [RyanWalker277/EcoJoy#9]
# Complete the Blogs Section

## Description
-Make a frontend interface for writing blogs as a seperate page
-Connect the interface to the backend blogs model
-Make the url path for the blog interface and link it to the frontend

## Expected outcomes

A working blogs section on the website

## Skills

Python, Django

## Possible mentors

[Anvansh](https://github.com/RyanWalker277)

## Expected project size

5 hours.

## Difficulty

Easy

**Comment by RyanWalker277** [comment]
# Use This Proposal Template as a Reference to write your own proposal for Msoc

# Your Issue Name

### Your Background and Technical Skills.
<hr>

### What problem are you trying to solve and Your Approach?
<hr>

###  Your Timeline to solve the problem.
<hr>

**Comment by RyanWalker277** [comment]
# Example of Proposal.


# Improve the generated PDF in the PDF/LaTeX backend

### About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 2 years. I
have experienced in Python , JavaScript, and Dart[Flutter] and I am currently learning Julia. I organized events on Open-Source in my College and I am the founding member of an Open-Source community [fossc](https://www.saynotocp.org/) where I mentor Students in their Open-Source Journey. For more information about me You can head over to my [website](https://kanishkpachauri.netlify.app/)
<hr>

### Issue - Intermittent CI failures with PDF builds 
Issue - The "PDF/LaTeX backend" stage often fails on CI, causing the docs not to deploy (since they only deploy if that stage passes) Restarting the build usually fixes it though.

## Proposed Solution….
● Fixing any bug on the CI end.
● Debug any issue in the test of the LaTeX backend
● Rewriting guided Tests for it so that it can be fixed throughout the process.
<hr>

###  TimeLine
## May 20 - June 12
Community bonding, understanding Documenter.jl Codebase, re-scoping project implementation/timeline with help from mentors.

## June 13 - June 23
Learning Julia Essentials and other essentials for integration and fixing of issue #1196 and #1467 and #1342 .

## June 24 - July 15
Adding the Proposed Solution for the issue #1196 and #1467

<hr>

**Comment by prabs222** [comment]
Hello sir, I want to contribute to this issue.

**Comment by prabs222** [comment]
@RyanWalker277 sir i am planning to create a functionality in which 
- Only the registered and authenticated users can write a new blog.
- anyone can view all the blogs.

Do I also need to create the comment section?
if yes then please brief that anyone can comment or only the users who are authenticated?

Please tell me whether I am on the right track or not?

**Comment by RyanWalker277** [comment]
Hey @prabs222 , yes you are on the right track! The idea is really good and more than I initially intended to do.For the blogs section , you can allow only authenticated users to write blogs and allow anyone to comment by providing their names. You should raise a new issue and regarding the same , so that I can assign appropriate difficulty level which rewards your efforts.

**Comment by prabs222** [comment]
@RyanWalker277 Thankyou sir. Sir I have raised a new issue with all the above mentioned points and also added some extra features for the proper and efficient working in all cases. Sir please review the issue. Thanks again!

**Comment by RyanWalker277** [comment]
I have assigned you the issue , you can start working on it

**Comment by prabs222** [comment]
#17 Completed the Blogs Section
